arreglo [7] de cadena [8] pollo
arreglo [7] de cadena [12] pollos
entero numero
inicio 
	pollos [3]<-"5"
	pollos [1]<-"yo"
	pollos [2]<-"Tu"
	pollos [4]<-"8"
	pollos [5]<-"88"
	pollos [6]<-"59"
	pollos [7]<-"R*"
	escriba "Impresion del contenido del arreglo pollos"
	llamar nueva_linea
		para numero<-1 hasta 7 haga
		llamar nueva_linea
		escriba "la posicion[", numero, "] contiene: ", pollos [numero]
		fin para
fin
